CC=mpicc
FC=mpif90
CFLAGS=-std=c99 -fPIC -Dpic -shared -lgfortran -lmechanic -lhdf5 -lhdf5_hl
FFLAGS=-std=f2003 -fPIC -Dpic
EXT=so

all:
	${CC} ${CFLAGS} -c mechanic_module_ex_ffc.c
	${FC} ${FFLAGS} -c mechanic_module_ex_ffc_fortran.F90 
	${CC} ${CFLAGS} -o libmechanic_module_ex_ffc.${EXT} mechanic_module_ex_ffc.o mechanic_module_ex_ffc_fortran.o 

clean:
	rm -f *.so *.dylib *.o *.mod *.h5
