#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

srcdir = '.'
blddir = '../../build'

def configure(conf):
  pass

def build(bld):
  obj = bld.new_task_gen('cc', 'cstaticlib')
  obj.find_sources_in_dirs(".")
  obj.include = "."
  obj.target = 'mechanic-core'
  pass

