CC=mpicc
CFLAGS=-std=c99 -fPIC -Dpic -shared -lmechanic -lhdf5 -lhdf5_hl
EXT=so

examples=\
	mechanic_module_ex_map.${EXT} \
	mechanic_module_ex_mandelbrot.${EXT} \
	mechanic_module_ex_setup.${EXT} \
	mechanic_module_ex_poolsetup.${EXT} \
	mechanic_module_ex_prepareprocess.${EXT} \
	mechanic_module_ex_createpool.${EXT} \
	mechanic_module_ex_changepoollayout.${EXT} \
	mechanic_module_ex_changepoollayout2.${EXT} \
	mechanic_module_ex_datatypes.${EXT} \
	mechanic_module_ex_dim.${EXT} \
	mechanic_module_ex_attr.${EXT} \
	mechanic_module_ex_reset.${EXT} \
	mechanic_module_ex_pool.${EXT} \
	mechanic_module_ex_poolsize.${EXT} \
	mechanic_module_ex_dset.${EXT} \
	mechanic_module_ex_node.${EXT} \
	mechanic_module_ex_loop.${EXT} \
	mechanic_module_ex_readfile.${EXT} \
	mechanic_module_ex_readfile_setup.${EXT} \
	mechanic_module_ex_ga.${EXT} \
	mechanic_module_ex_rngs.${EXT} \
	mechanic_module_ex_taskcheckpoint.${EXT}

%.so: %.c
	${CC} -o lib$@ $< ${CFLAGS}

%.dylib: %.c
	${CC} -o lib$@ $< ${CFLAGS}

all: ${examples}

clean:
	rm -f *.o *.dylib *.so *.h5
