#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen('cc', 'shlib')
obj.source = bld.glob('*.c')
obj.includes = ". ../core"
obj.uselib_local = "core corelib"
obj.target = 'mechanic_module_module'
obj.name = 'module'
