#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen(features='fortran fmodule')
obj.source = bld.glob('*.F03')
obj.includes = "."
obj.export_incdirs = "."
obj.target = 'mechanic_fortran'
obj.name = 'fortran'
obj.after = 'core'

bld.install_files('${PREFIX}/include', 'mechanic_fortran.mod')
