#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

import fortran

obj = bld.new_task_gen(features='fortran fstaticlib')
obj.find_sources_in_dirs(".")
obj.includes = "."
obj.export_incdirs = "."
obj.target = 'mechanic_fortran'
obj.name = 'fortran'

bld.install_files('${PREFIX}/include', 'mechanic_fortran.mod')
