#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen(features='fortran fshlib')
obj.source = bld.glob('*.F03')
obj.includes = ". ../../../fortran"
obj.export_incdirs = "."
obj.target = 'mechanic_module_f2003'
obj.name = 'f2003'
obj.after = 'fortran'

bld.install_files('${PREFIX}/lib', 'libmechanic_module_f2003.'+bld.env['MECHANIC_LIBEXT'])
