#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen('cc', 'cstaticlib')
obj.source = bld.glob('*.c')
obj.includes = ". ../../core"
obj.uselib = 'core'
obj.target = 'mechanic_mode_gpu'
obj.name = 'gpu'

