#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen('cc', 'cstaticlib')
obj.source = bld.glob('*.c')
obj.includes = ". ../../core"
obj.uselib_local = "core"
obj.target = 'mechanic_engine_gpu'
obj.name = 'gpu-static'

obj = bld.new_task_gen('cc', 'shlib')
obj.source = bld.glob('*.c')
obj.includes = ". ../../core"
obj.uselib_local = "core"
obj.target = 'mechanic_engine_gpu'
obj.name = 'gpu-shared'
  
bld.install_files('${PREFIX}/include/mechanic','mechanic_engine_gpu.h')
