#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen('cc', 'cstaticlib')
obj.find_sources_in_dirs(".")
obj.includes = ". ../../core"
obj.uselib_local = 'core'
obj.target = 'mechanic_mode_multifarm'
obj.name = 'multifarm'

