" Basics
:set nocompatible
:set nobackup
:set ruler
:set pastetoggle=<F11>
:set fo=tcrqn
:syntax on
:filetype on
filetype plugin on
filetype indent on

" Various syntax highlighting
:autocmd BufRead,BufNewFile *.f03 set filetype=fortran
:autocmd BufRead,BufNewFile *.F03 set filetype=fortran

:autocmd FileType c,cpp :set cindent
:set grepprg=grep\ -nH\ $*
:set comments=s1:/**,mb:\ *,elx:*/

" Coding standard
:set nu
:set textwidth=90
:set shiftwidth=2
:set tabstop=2
:set smarttab
:set expandtab
:set autoindent
:set smartindent
:set makeprg=make

" This will highlight lines longer than 80 chars
:highlight OverLength ctermbg=red ctermfg=white guibg=#592929
:match OverLength /\%80v.*/
:let c_space_errors = 1 

