#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen('cc', 'cshlib')
obj.source = bld.glob('*.c')
obj.includes = ". ../../core"
obj.uselib_local = "core"
obj.uselib = "M"
obj.target = 'mechanic_module_mandelbrot'
obj.name = 'mandelbrot'

