CC=mpicc
CFLAGS=-std=c99 -fPIC -Dpic -shared -lmechanic2 -lhdf5 -lhdf5_hl
EXT=dylib

examples=\
	mechanic_module_ex_map.${EXT} \
	mechanic_module_ex_mandelbrot.${EXT} \
	mechanic_module_ex_setup.${EXT} \
	mechanic_module_ex_prepareprocess.${EXT} \
	mechanic_module_ex_createpool.${EXT} \
	mechanic_module_ex_changepoollayout.${EXT} \
	mechanic_module_ex_changepoollayout2.${EXT} \
	mechanic_module_ex_datatypes.${EXT} \
	mechanic_module_ex_dim.${EXT} \
	mechanic_module_ex_attr.${EXT} \
	mechanic_module_ex_reset.${EXT} \
	mechanic_module_ex_pool.${EXT} \
	mechanic_module_ex_dset.${EXT} 

%.so: %.c
	${CC} -o lib$@ $< ${CFLAGS}

%.dylib: %.c
	${CC} -o lib$@ $< ${CFLAGS}

all: ${examples}

clean:
	rm -f *.o *.dylib *.so *.h5
