#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

obj = bld.new_task_gen('cc', 'cstaticlib')
obj.find_sources_in_dirs(".")
obj.includes = "."
obj.export_incdirs = "."
obj.uselib = "READCONFIG"
obj.target = 'mechanic_core'
obj.name = 'core'

bld.install_files('${PREFIX}/include', 'mechanic.h')
