#!/usr/bin/env python
# wscript for Mechanic
# Mariusz Slonina, 2010
# encoding: utf-8

bld.add_subdirs('core engines modes modules')
obj = bld.new_task_gen('cc', 'cprogram')
obj.uselib_local = 'farm masteralone multifarm gpu odex taylor core'
obj.includes = '. core'
obj.ccflags = '-rdynamic'
obj.source = 'mechanic.c'
obj.target = 'mechanic'
obj.uselib = 'READCONFIG HDF5 POPT M'

